name: Build
run-name: Build

on:
  push:

jobs:
  publish:
    name: Build & Push Dockerfile
    uses: ztimson/actions/.github/workflows/docker.yaml@develop
    with:
      name: ztimson/node-exporter
      repository: ${{github.server_url}}/${{github.repository}}.git
      pass: ${{secrets.DEPLOY_TOKEN}}

  tag:
    name: Tag Version
    needs: publish
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: Clone Repository
        uses: ztimson/actions/clone@develop

      - name: Get Version Number
        run: echo "VERSION=$(cat package.json | grep version | grep -Eo ':.+' | grep -Eo '[[:alnum:]\.\/\-]+')" >> $GITHUB_ENV

      - name: Tag Version
        uses: ztimson/actions/tag@develop
        with:
          tag: ${{env.VERSION}}
